apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cas.app.example.com
spec:
  group: app.example.com
  names:
    kind: CAs
    listKind: CAsList
    plural: cas
    singular: cas
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              properties:
                labels:
                  properties:
                    app:
                      type: string
                    org:
                      type: string
                    role:
                      type: string
                  required:
                  - app
                  - role
                  - org
                  type: object
                name:
                  type: string
              required:
              - name
              - labels
              type: object
            spec:
              properties:
                replicas:
                  format: int64
                  type: integer
                template:
                  properties:
                    metadata:
                      properties:
                        labels:
                          properties:
                            role:
                              type: string
                          required:
                          - role
                          type: object
                        name:
                          type: string
                      required:
                      - name
                      - labels
                      type: object
                    spec:
                      properties:
                        containers:
                          properties:
                            command:
                              items:
                                type: string
                              type: array
                            image:
                              type: string
                            name:
                              type: string
                            ports:
                              items:
                                properties:
                                  containerPort:
                                    format: int64
                                    type: integer
                                required:
                                - containerPort
                                type: object
                              type: array
                          required:
                          - name
                          - image
                          - ports
                          - command
                          type: object
                        restartPolicy:
                          type: string
                      required:
                      - restartPolicy
                      - containers
                      type: object
                  required:
                  - metadata
                  - spec
                  type: object
              required:
              - replicas
              - template
              type: object
          required:
          - apiVersion
          - kind
          - metadata
          - spec
          type: object
        status:
          properties:
            certiAuth:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - certiAuth
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
